import type {
  Affiliate,
  Referral,
  Conversion,
  Payout,
  PayoutRun,
  MarketingAsset,
  AffiliateTier,
  Milestone,
  Contest,
  DiscountCode,
  Broadcast,
  Message,
  SupportTicket,
  AffiliateStats,
  ChartDataPoint,
} from "../types";

export const mockAffiliate: Affiliate = {
  id: "aff_001",
  user_id: "user_001",
  name: "Sarah Chen",
  email: "sarah@example.com",
  referral_code: "SARAH2024",
  tier: "gold",
  status: "active",
  commission_rate: 25,
  total_earnings: 4280.5,
  pending_earnings: 340.0,
  total_clicks: 12450,
  total_conversions: 186,
  payment_method: "paypal",
  payment_email: "sarah@example.com",
  created_at: "2024-01-15T10:00:00Z",
  updated_at: "2024-11-20T15:30:00Z",
};

export const mockStats: AffiliateStats = {
  total_clicks: 12450,
  total_conversions: 186,
  total_earnings: 4280.5,
  pending_earnings: 340.0,
  conversion_rate: 1.49,
  clicks_today: 47,
  earnings_this_month: 620.0,
};

export const mockChartData: ChartDataPoint[] = Array.from(
  { length: 30 },
  (_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (29 - i));
    return {
      date: date.toISOString().split("T")[0],
      clicks: Math.floor(Math.random() * 200) + 50,
      conversions: Math.floor(Math.random() * 15) + 1,
      revenue: Math.floor(Math.random() * 500) + 50,
    };
  },
);

export const mockReferrals: Referral[] = [
  {
    id: "ref_001",
    affiliate_id: "aff_001",
    visitor_id: "vis_001",
    referral_code: "SARAH2024",
    ip_address: null,
    user_agent: null,
    landing_page: "/pricing",
    clicked_at: "2024-11-20T14:30:00Z",
    converted: true,
    converted_at: "2024-11-21T09:15:00Z",
    converted_user_id: "user_new_001",
  },
  {
    id: "ref_002",
    affiliate_id: "aff_001",
    visitor_id: "vis_002",
    referral_code: "SARAH2024",
    ip_address: null,
    user_agent: null,
    landing_page: "/features",
    clicked_at: "2024-11-19T11:20:00Z",
    converted: false,
    converted_at: null,
    converted_user_id: null,
  },
  {
    id: "ref_003",
    affiliate_id: "aff_001",
    visitor_id: "vis_003",
    referral_code: "SARAH2024",
    ip_address: null,
    user_agent: null,
    landing_page: "/",
    clicked_at: "2024-11-18T08:45:00Z",
    converted: true,
    converted_at: "2024-11-19T16:30:00Z",
    converted_user_id: "user_new_002",
  },
  {
    id: "ref_004",
    affiliate_id: "aff_001",
    visitor_id: "vis_004",
    referral_code: "SARAH2024",
    ip_address: null,
    user_agent: null,
    landing_page: "/pricing",
    clicked_at: "2024-11-17T20:10:00Z",
    converted: true,
    converted_at: "2024-11-18T11:00:00Z",
    converted_user_id: "user_new_003",
  },
  {
    id: "ref_005",
    affiliate_id: "aff_001",
    visitor_id: "vis_005",
    referral_code: "SARAH2024",
    ip_address: null,
    user_agent: null,
    landing_page: "/features",
    clicked_at: "2024-11-16T15:55:00Z",
    converted: false,
    converted_at: null,
    converted_user_id: null,
  },
];

export const mockConversions: Conversion[] = [
  {
    id: "conv_001",
    affiliate_id: "aff_001",
    referral_id: "ref_001",
    user_id: "user_new_001",
    sale_amount: 99.0,
    commission_amount: 24.75,
    status: "approved",
    created_at: "2024-11-21T09:15:00Z",
  },
  {
    id: "conv_002",
    affiliate_id: "aff_001",
    referral_id: "ref_003",
    user_id: "user_new_002",
    sale_amount: 199.0,
    commission_amount: 49.75,
    status: "pending",
    created_at: "2024-11-19T16:30:00Z",
  },
  {
    id: "conv_003",
    affiliate_id: "aff_001",
    referral_id: "ref_004",
    user_id: "user_new_003",
    sale_amount: 49.0,
    commission_amount: 12.25,
    status: "paid",
    created_at: "2024-11-18T11:00:00Z",
  },
];

export const mockPayouts: Payout[] = [
  {
    id: "pay_001",
    affiliate_id: "aff_001",
    amount: 500.0,
    status: "completed",
    payment_method: "paypal",
    transaction_id: "TXN_ABC123",
    processed_at: "2024-11-01T10:00:00Z",
    created_at: "2024-10-31T23:59:00Z",
  },
  {
    id: "pay_002",
    affiliate_id: "aff_001",
    amount: 340.0,
    status: "pending",
    payment_method: "paypal",
    transaction_id: null,
    processed_at: null,
    created_at: "2024-11-20T23:59:00Z",
  },
  {
    id: "pay_003",
    affiliate_id: "aff_001",
    amount: 750.0,
    status: "completed",
    payment_method: "paypal",
    transaction_id: "TXN_DEF456",
    processed_at: "2024-10-01T10:00:00Z",
    created_at: "2024-09-30T23:59:00Z",
  },
];

export const mockAssets: MarketingAsset[] = [
  {
    id: "asset_001",
    name: "MuseKit Banner 728x90",
    type: "banner",
    content: "https://musekit.io/assets/banner-728x90.png",
    preview_url: null,
    dimensions: "728x90",
    created_at: "2024-06-01T00:00:00Z",
  },
  {
    id: "asset_002",
    name: "MuseKit Banner 300x250",
    type: "banner",
    content: "https://musekit.io/assets/banner-300x250.png",
    preview_url: null,
    dimensions: "300x250",
    created_at: "2024-06-01T00:00:00Z",
  },
  {
    id: "asset_003",
    name: "Email Template - Welcome",
    type: "email",
    content:
      "Hey {name}! I've been using MuseKit for my music production and it's amazing. Use my link to get 20% off your first month!",
    preview_url: null,
    dimensions: null,
    created_at: "2024-07-15T00:00:00Z",
  },
  {
    id: "asset_004",
    name: "Social Post Template",
    type: "social",
    content:
      "Transform your music production workflow with @MuseKit! Use my referral link for an exclusive discount. #MuseKit #MusicProduction",
    preview_url: null,
    dimensions: null,
    created_at: "2024-08-01T00:00:00Z",
  },
];

export const mockTiers: AffiliateTier[] = [
  {
    id: "tier_001",
    name: "Bronze",
    slug: "bronze",
    commission_rate: 15,
    min_sales: 0,
    min_revenue: 0,
    benefits: ["Basic analytics", "Standard banners", "Monthly payouts"],
  },
  {
    id: "tier_002",
    name: "Silver",
    slug: "silver",
    commission_rate: 20,
    min_sales: 10,
    min_revenue: 500,
    benefits: [
      "Advanced analytics",
      "Custom banners",
      "Bi-weekly payouts",
      "Priority support",
    ],
  },
  {
    id: "tier_003",
    name: "Gold",
    slug: "gold",
    commission_rate: 25,
    min_sales: 50,
    min_revenue: 5000,
    benefits: [
      "Full analytics suite",
      "Custom landing pages",
      "Weekly payouts",
      "Dedicated manager",
      "Early access to features",
    ],
  },
  {
    id: "tier_004",
    name: "Platinum",
    slug: "platinum",
    commission_rate: 30,
    min_sales: 200,
    min_revenue: 25000,
    benefits: [
      "Real-time analytics",
      "Co-branded pages",
      "Daily payouts",
      "VIP support",
      "Revenue share bonuses",
      "Exclusive events",
    ],
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: "ms_001",
    name: "First Sale",
    description: "Complete your first referral sale",
    requirement_type: "sales",
    requirement_value: 1,
    reward_type: "bonus",
    reward_value: "$25 bonus",
  },
  {
    id: "ms_002",
    name: "10 Sales Club",
    description: "Reach 10 total sales",
    requirement_type: "sales",
    requirement_value: 10,
    reward_type: "tier_upgrade",
    reward_value: "Silver tier unlock",
  },
  {
    id: "ms_003",
    name: "Revenue Milestone",
    description: "Generate $5,000 in referral revenue",
    requirement_type: "revenue",
    requirement_value: 5000,
    reward_type: "bonus",
    reward_value: "$500 bonus",
  },
  {
    id: "ms_004",
    name: "Referral Champion",
    description: "Refer 100 visitors",
    requirement_type: "referrals",
    requirement_value: 100,
    reward_type: "badge",
    reward_value: "Champion badge",
  },
];

export const mockContests: Contest[] = [
  {
    id: "contest_001",
    name: "Holiday Sales Sprint",
    description:
      "Top affiliates earn bonus commissions during the holiday season",
    start_date: "2024-12-01T00:00:00Z",
    end_date: "2024-12-31T23:59:59Z",
    prize_description: "1st: $1000, 2nd: $500, 3rd: $250",
    status: "active",
    metric: "revenue",
  },
  {
    id: "contest_002",
    name: "New Year Referral Rush",
    description: "Most conversions in January wins premium rewards",
    start_date: "2025-01-01T00:00:00Z",
    end_date: "2025-01-31T23:59:59Z",
    prize_description: "Top 10 affiliates get 5% commission boost for Q1",
    status: "draft",
    metric: "conversions",
  },
];

export const mockDiscountCodes: DiscountCode[] = [
  {
    id: "dc_001",
    code: "SARAH20",
    affiliate_id: "aff_001",
    discount_type: "percentage",
    discount_value: 20,
    max_uses: 100,
    current_uses: 34,
    expires_at: "2025-03-31T23:59:59Z",
    status: "active",
    created_at: "2024-10-01T00:00:00Z",
  },
  {
    id: "dc_002",
    code: "MUSEKIT10",
    affiliate_id: null,
    discount_type: "percentage",
    discount_value: 10,
    max_uses: null,
    current_uses: 892,
    expires_at: null,
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "dc_003",
    code: "HOLIDAY50",
    affiliate_id: null,
    discount_type: "fixed",
    discount_value: 50,
    max_uses: 200,
    current_uses: 200,
    expires_at: "2024-12-31T23:59:59Z",
    status: "expired",
    created_at: "2024-12-01T00:00:00Z",
  },
];

export const mockBroadcasts: Broadcast[] = [
  {
    id: "bc_001",
    title: "Holiday Commission Boost!",
    content:
      "Great news! All commissions are boosted by 5% for the holiday season. Get sharing!",
    sent_by: "admin",
    sent_at: "2024-12-01T09:00:00Z",
    recipient_count: 247,
  },
  {
    id: "bc_002",
    title: "New Marketing Materials Available",
    content:
      "We've added new banners and social templates. Check the Resources section for fresh content.",
    sent_by: "admin",
    sent_at: "2024-11-15T10:00:00Z",
    recipient_count: 234,
  },
];

export const mockMessages: Message[] = [
  {
    id: "msg_001",
    affiliate_id: "aff_001",
    sender_type: "admin",
    subject: "Welcome to Gold Tier!",
    content:
      "Congratulations on reaching Gold tier! Your commission rate has been increased to 25%.",
    read: true,
    created_at: "2024-11-01T09:00:00Z",
  },
  {
    id: "msg_002",
    affiliate_id: "aff_001",
    sender_type: "affiliate",
    subject: "Custom landing page request",
    content:
      "Hi, I'd like to request a custom landing page for my YouTube audience. Can you help?",
    read: true,
    created_at: "2024-11-05T14:30:00Z",
  },
  {
    id: "msg_003",
    affiliate_id: "aff_001",
    sender_type: "admin",
    subject: "Re: Custom landing page request",
    content:
      "Of course! We'll set one up for you. Can you share your branding preferences?",
    read: false,
    created_at: "2024-11-06T10:00:00Z",
  },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: "ticket_001",
    affiliate_id: "aff_001",
    subject: "Tracking link not working",
    description:
      "My tracking link seems to not register clicks from Instagram stories.",
    status: "resolved",
    priority: "high",
    created_at: "2024-10-15T08:00:00Z",
    updated_at: "2024-10-16T14:00:00Z",
  },
  {
    id: "ticket_002",
    affiliate_id: "aff_001",
    subject: "Payout delay",
    description: "My October payout hasn't been processed yet.",
    status: "open",
    priority: "medium",
    created_at: "2024-11-10T09:00:00Z",
    updated_at: "2024-11-10T09:00:00Z",
  },
];

export const mockAffiliates: Affiliate[] = [
  mockAffiliate,
  {
    id: "aff_002",
    user_id: "user_002",
    name: "Alex Rivera",
    email: "alex@example.com",
    referral_code: "ALEX2024",
    tier: "silver",
    status: "active",
    commission_rate: 20,
    total_earnings: 1850.0,
    pending_earnings: 120.0,
    total_clicks: 5680,
    total_conversions: 72,
    payment_method: "stripe",
    payment_email: "alex@example.com",
    created_at: "2024-03-20T10:00:00Z",
    updated_at: "2024-11-18T12:00:00Z",
  },
  {
    id: "aff_003",
    user_id: "user_003",
    name: "Jordan Lee",
    email: "jordan@example.com",
    referral_code: "JORDAN24",
    tier: "bronze",
    status: "active",
    commission_rate: 15,
    total_earnings: 450.0,
    pending_earnings: 65.0,
    total_clicks: 2100,
    total_conversions: 28,
    payment_method: "paypal",
    payment_email: "jordan@example.com",
    created_at: "2024-06-10T10:00:00Z",
    updated_at: "2024-11-19T09:00:00Z",
  },
  {
    id: "aff_004",
    user_id: "user_004",
    name: "Maya Patel",
    email: "maya@example.com",
    referral_code: "MAYA2024",
    tier: "platinum",
    status: "active",
    commission_rate: 30,
    total_earnings: 12500.0,
    pending_earnings: 890.0,
    total_clicks: 34200,
    total_conversions: 420,
    payment_method: "bank_transfer",
    payment_email: "maya@example.com",
    created_at: "2023-08-01T10:00:00Z",
    updated_at: "2024-11-20T16:00:00Z",
  },
  {
    id: "aff_005",
    user_id: "user_005",
    name: "Chris Thompson",
    email: "chris@example.com",
    referral_code: "CHRIS24",
    tier: "bronze",
    status: "pending",
    commission_rate: 15,
    total_earnings: 0,
    pending_earnings: 0,
    total_clicks: 0,
    total_conversions: 0,
    payment_method: null,
    payment_email: null,
    created_at: "2024-11-18T10:00:00Z",
    updated_at: "2024-11-18T10:00:00Z",
  },
];

export const mockPayoutRuns: PayoutRun[] = [
  {
    id: "pr_001",
    total_amount: 15420.0,
    affiliate_count: 45,
    status: "completed",
    processed_by: "admin_001",
    created_at: "2024-11-01T00:00:00Z",
    completed_at: "2024-11-01T02:00:00Z",
  },
  {
    id: "pr_002",
    total_amount: 8750.0,
    affiliate_count: 32,
    status: "pending",
    processed_by: "admin_001",
    created_at: "2024-12-01T00:00:00Z",
    completed_at: null,
  },
];
