import { emailWrapper, defaultBrand } from './shared';
import type { BrandSettings } from '../lib/supabase';

export interface KPIReportEmailProps {
  userName: string;
  period: string;
  periodType: 'weekly' | 'monthly';
  totalUsers: string;
  newUsers: string;
  activeUsers: string;
  revenue: string;
  mrr: string;
  churnRate: string;
  dashboardUrl: string;
  brand?: Partial<BrandSettings>;
}

export function renderKPIReportEmail(props: KPIReportEmailProps): string {
  const brand = { ...defaultBrand, ...props.brand };

  const content = `
    <h2>${props.periodType === 'weekly' ? 'Weekly' : 'Monthly'} KPI Report</h2>
    <p>Hi ${props.userName},</p>
    <p>Here's your ${props.periodType} metrics summary for <strong>${props.period}</strong>.</p>

    <table class="kpi-table">
      <thead>
        <tr>
          <th>Metric</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Total Users</td>
          <td><span class="kpi-value">${props.totalUsers}</span></td>
        </tr>
        <tr>
          <td>New Users</td>
          <td><span class="kpi-value">${props.newUsers}</span></td>
        </tr>
        <tr>
          <td>Active Users</td>
          <td><span class="kpi-value">${props.activeUsers}</span></td>
        </tr>
        <tr>
          <td>Revenue</td>
          <td><span class="kpi-value">${props.revenue}</span></td>
        </tr>
        <tr>
          <td>MRR</td>
          <td><span class="kpi-value">${props.mrr}</span></td>
        </tr>
        <tr>
          <td>Churn Rate</td>
          <td><span class="kpi-value">${props.churnRate}</span></td>
        </tr>
      </tbody>
    </table>

    <div style="text-align: center; margin: 24px 0;">
      <a href="${props.dashboardUrl}" class="btn">View Full Dashboard</a>
    </div>
    <p class="text-muted">This report was automatically generated by ${brand.appName}.</p>
  `;

  return emailWrapper(content, brand);
}

export function kpiReportEmailPlainText(props: KPIReportEmailProps): string {
  const brand = { ...defaultBrand, ...props.brand };
  return `${props.periodType === 'weekly' ? 'Weekly' : 'Monthly'} KPI Report

Hi ${props.userName},

Here are your metrics for ${props.period}:

Total Users: ${props.totalUsers}
New Users: ${props.newUsers}
Active Users: ${props.activeUsers}
Revenue: ${props.revenue}
MRR: ${props.mrr}
Churn Rate: ${props.churnRate}

View full dashboard: ${props.dashboardUrl}

© ${new Date().getFullYear()} ${brand.appName}`;
}
